version: "2"

services:
  db:
    image: postgres:11.2
    restart: always
    environment:
      - POSTGRES_USER=netbox
      - POSTGRES_PASSWORD=netbox
      - POSTGRES_DB=netbox
    ports:
      - 5432:5432
    volumes:
      - ./2019-05-03.sql:/docker-entrypoint-initdb.d/2019-05-03.sql